export const projects = [
    {
      projectName: "Personal Website",
      type: "Personal",
      category: "Web Development",
      description: "The porfolio website you are currently viewing!",
      date: "2025",
      link: "https://github.com/kazuhidelee/Personal_Website",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "SoleSpeaks",
      type: "Academic",
      category: "Web Development",
      description: "The porfolio website you are currently viewing!",
      date: "2025",
      link: "https://eecs497.lkellar.org/",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Bubble! - Learn Science",
      type: "Industrial",
      category: "Web Development",
      description: "A web application that aids students with lower resource backgrounds...",
      date: "2023",
      link: "https://github.com/kalifrancisco/bubble-nextjs",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Arbor Advisor",
      type: "Industrial",
      category: "Web Development",
      description: "An user-centric website aimed to condense resources for international, out of state, and first generation students in the Washtenaw County area focused on accommodating to various necessities such as groceries and transportation",
      date: "2023",
      link: "https://mandyschen.github.io/WashtenawWelcome/",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "AI Chatbot",
      type: "Personal",
      category: "Web Development",
      description: "An AI chatbot website that uses the OpenAI API key",
      date: "2024",
      link: "https://github.com/kazuhidelee/AI_chatbot",
      projectOverview: "This is a simple chat application using React.js and the Chat UI Kit library from Chatscope. The application allows users to interact with an AI chatbot powered by OpenAI where users can type messages, which are then sent to the backend (OpenAI's API). First, the message typed by the user is added to the messages array and it will be displayed in the chat UI. Then, the message will be processed into format that is suitable for the Open AI request format. After the conversion, the funciton will put all the required information (model, api message, system message) in JSON format and send it to the API. If processed successfully, the API will return response message from ChatGPT, and the function will display the message content onto the chat UI.",
      photo:"",
    },
    {
      projectName: "Windrose API",
      type: "Industrial",
      category: "Web Development",
      description: "A public API that fetches historical windose data from Southeast Michigan region; Used in the air quality map research project",
      date: "2024",
      link: "https://github.com/kazuhidelee/windrose_api",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Concordia",
      type: "Industrial",
      category: "Mobile Development",
      description: "A mobile application for 200+ global volunteers to streamline support efforts, impacting 2.8 million people in the Dominican Republic",
      date: "2024",
      link: "private",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Search Engine",
      type: "Academic",
      category: "Distributed System",
      description: "A scalable search engine similar to Google and Bing using MapReduce for parallel data processing, incorporating tf-idf and PageRank algorithms to optimize information retrieval and link analysis",
      date: "2024",
      link: "private",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Mapreduce paradigm",
      type: "Academic",
      category: "Distributed System",
      description: "A single machine, multi-process, multi-threaded server that executes user-submitted MapReduce Jobs",
      date: "2024",
      link: "private",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Thread Library",
      type: "Academic",
      category: "Operating System",
      description: "A kernel level thread library similar to the STL library in C++; includes cpu, threads, mutex, and cv classes",
      date: "2025",
      link: "private",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "External Pager",
      type: "Academic",
      category: "Operating System",
      description: "An external pager, which manges virtual memory for application processes",
      date: "2025",
      link: "private",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Network File System",
      type: "Academic",
      category: "Operating System",
      description: "A muti-threaded, secure network file Server that allows clients to read, write, and delete files on the server",
      date: "2025",
      link: "private",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "BW Colorization",
      type: "Academic",
      category: "Computer Vision",
      description: "An TensorFlow image colorization model inspired by the paper Colorful image Colorization by Zhang et al.",
      date: "2024",
      link: "https://github.com/kazuhidelee/BWToColorized",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Mission Valentine",
      type: "Personal",
      category: "Game Development",
      description: "A Valentine themed mini game that inlcudes dodging game machanisms and a lot of cute pixel arts drew by me :-)",
      date: "2025",
      link: "https://github.com/kazuhidelee/mission_valentine",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Monte Carlo Tree Search AI",
      type: "Academic",
      category: "Artificial Intelligent",
      description: "Implemation of the Monte Carlo Tree Search Algorithm part of the AlphaZero in the context of the game 'Othello'",
      date: "2024",
      link: "https://github.com/kazuhidelee/MCTS",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Image Classifier",
      type: "Academic",
      category: "Artificial Intelligent",
      description: "A PyTorch convolutaional neural network that is aimed to classify images",
      date: "2024",
      link: "https://github.com/kazuhidelee/Image-Classification",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Min-Max Game Agent",
      type: "Academic",
      category: "Artificial Intelligent",
      description: "A Tic-Tac-Toe and Connect-4 AI agent using the minimax with alpha-beta pruning algorithm",
      date: "2024",
      link: "https://github.com/kazuhidelee/minimax-game-ai",
      projectOverview: "",
      photo:"",
    },
    {
      projectName: "Maze Search Algorithms",
      type: "Academic",
      category: "Artificial Intelligent",
      description: "An AI agent that searches a path in a maze using BFS, DFS, UCS, A-start search algorithms",
      date: "2024",
      link: "https://github.com/kazuhidelee/maze-search-algorithms",
      projectOverview: "",
      photo:"",
    },
    
  ];



export const categoryColors = {
	"Distributed System": "#cad0eb",
	"Operating System": "#d1e3c9",
	"Web Development": "#b2dde1",
	"Computer Vision": "#e2c7e5",
	"Game Development": "#feddaa",
	"Artificial Intelligent": "#fffcd0",
};



